### ISSUE TITLE
Warn the user if specifying an inaccessible slave-local file for logging

### ISSUE THREAD

**Issue by epeld** [mesos/logstash#24]
Currently, the user can specify files from the mesos slave itself that he wishes to log (e.g /var/log/mesos/mesos-info.log). However, if he hasn't also specified e.g /var/log/mesos as a volume (in his logstash-mesos configuration), that file will not be accessible from within the executor which means we cannot log it.

We should warn the user whenever we encounter 'host-path's in our configurations that are not contained inside a volume.

**Comment by jhftrifork** [comment]
@mwl I think this refers to an older implementation of Mesos slave file logging. I think it's saying that if a pattern in `--executor.file-path` does not match a file, we should warn the user. I think this is inappropriate now because (a) Logstash is in control of interpreting the file path patterns, and (b) it's not really an error for a pattern to not match a file; e.g. it might match an expected file in the future. Closing for now.
