### ISSUE TITLE
Scheduler should remove its frameworkId from zookeeper on shutdown

### ISSUE THREAD

**Issue by epeld** [mesos/logstash#26]
Currently it is not possible to restart a scheduler once it has terminated because the path `/logstash/frameworkId` already exists in zookeper and we get a collision.

The scheduler should make sure it erases its frameworkId as soon as it terminates so that it can be restarted.

**Comment by jhftrifork** [comment]
The ZK path `/logstash/frameworkId` represents the ID of the single Logstash framework registered with Mesos. The reason we store this is so that we can restart a scheduler under the same framework ID. The current behavior is that, when the scheduler starts, if a value exists at `/logstash/frameworkId`, the scheduler uses that value as its framework ID when registering with Mesos.

Therefore I don't think we have any collision problems, and this issue has been fixed.
